services:
    mongodb:
        image: zcube/bitnami-compat-mongodb:6.0.5
        container_name: mongodb
        hostname: mongodb
        restart: unless-stopped
        volumes:
            - mongodb-data:/data/db/
            - mongodb-log:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGODB_REPLICA_SET_MODE: primary
            ALLOW_EMPTY_PASSWORD: 'YES'
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"
        networks:
            - mongodb_network


volumes:
    mongodb-data:
        driver: local
        name: mongo-data
    mongodb-log:
        driver: local
        name: mongo-log

networks:
    mongodb_network:
        driver: bridge
        name: mongo-network